### ISSUE TITLE
مشکل در دانلود فایل

### ISSUE THREAD

**Issue by MohammadBadzohreh** [cyaxaress/lms#10]
سلام  خسته نباشید من تو دانلود فایل ها دقیقا دستورات را درست دنبال کردم ولی متوجه نمیشم چرا دانلود نمیکنه و به جاش یه صفحه سفید بالا میاره
` static::$media = $media;
        $stream = Storage::readStream(static::getFilename());
        return response()->stream(function () use ($stream) {
            fpassthru($stream);
        }, 200, [
            'Content-Type' => Storage::mimeType(static::getFileName()),
            'Content-Disposition' => 'attachment; filename=' . static::$media->file_name . ';'
        ]);`

اینم کد ها تمامی متغیر ها رو چک کردم مقداراشون هم درست هستن ولی انگار رسپانس چیزی بر نمیگردونه

**Comment by cyaxaress** [comment]
قسمت 141 رو هم ببینید و بررسی کنید جواب بدید

**Comment by MohammadBadzohreh** [comment]
سلام اقای موافقی وقت بخیر متاسفانه حل نشد
