### ISSUE TITLE
مشکل ارسال ایمیل در ریست پسورد در هاست اشتراکی

### ISSUE THREAD

**Issue by alihastam** [cyaxaress/lms#11]
سلام آقای موافقی
من توی دوره شما شرکت کرده ام به مشکل برخورده ام.
من با استفاده از هاست اشتراکی تنظیمات ایمیل رو انجام داده ام و روی لاراول دقیقا همون تنظیمات رو انجام دادم ولی ایمیلی ارسال نمیشه و خطای تصویر زیر رو میده
با میل ترپ درسته ولی روی سرور با ایمیل سرور مشکل داره ارسال نمیشه 
میتونید در زیر مشخصات ایمیل
![2021-01-04_003710](https://user-images.githubusercontent.com/36451636/103490939-93363000-4e34-11eb-8e19-651e510b9845.jpg)
این تغییرات روی env
![2021-01-04_003549](https://user-images.githubusercontent.com/36451636/103490949-b82aa300-4e34-11eb-91a1-886db70c8721.jpg)
اینم خطاها
![2021-01-04_003404](https://user-images.githubusercontent.com/36451636/103490968-c973af80-4e34-11eb-8e39-00c804b83474.jpg)
![2021-01-04_003911](https://user-images.githubusercontent.com/36451636/103490975-d7293500-4e34-11eb-8dba-cfcde7e6dab8.jpg)

**Comment by cyaxaress** [comment]
با استفاده از اینترفیس وب به ایمیلتون برید و تست کنید که آیا میتونه ایمیل ارسال کنه.
-2 از صحت ایمیل و پسورد مطئن بشید.
3- از حالت بدون ssl و روی پورت 587 هم تست کنید

**Comment by alihastam** [comment]
همه این کارها رو امتحان کرده ام ولی جواب نداد  .
