### ISSUE TITLE
مشکل در user verify email 

### ISSUE THREAD

**Issue by saeid13623** [cyaxaress/lms#12]
با سلام خدمت شما آقای موافقی 
   verify email  زمانی که میخوایم با کد
انجام بدیم
  mailtrap کد ارسال میشه به
 verification.verify  ولی همون مشکل که برای روت 
بود رو نمایش میده
توفیلم هم با بازنویسی روت این مشکل حل میشه ولی وقتی من روت رو بازنویسی میکنم باز هم همون خطای 
نداشتن پارامتر  آی دی  {hash}
  رو نمایش میده اینم روت بازنویسی شده
Route::post('/email/verify','Auth\VerificationController@verify')->name('verification.verify');

**Comment by MH-Zarkhani** [comment]
remove route cache and try again

`php artisan route:clear`

or

`php artisan optimize:clear`
