### ISSUE TITLE
خروجی اکسل از دوره های خریداری شده 

### ISSUE THREAD

**Issue by alihastam** [cyaxaress/lms#13]
سلام میخواستم ازتون خواهش کنم خروجی اکسل با لاراول اکسل از دوره های خریداری شده بگیرید ، میدونم خیلی آسونه مشکل من  فقط بیگ دیتا هست مثلا فکر کنید 45 هزار تا رکورد دارید میخواید ازشون یه جا خروجی اکسل بگیرید چی کار میکنید؟

**Comment by cyaxaress** [comment]
سلام وقت بخیر . اگر مشکلتون بخاطر میزان بافر هست میتونید از Lazy Eager Loading استفاده کنید. 

از این اینک میتونید توضیحاتش رو بخونید:
https://laravel.com/docs/5.2/eloquent-relationships#lazy-eager-loading

**Comment by alihastam** [comment]
سلام مشکل رو با یه پیکج اکسل دیگه غیر از لاراول اکسل حل کردم.
