### ISSUE TITLE
too many requests

### ISSUE THREAD

**Issue by aaminhashemi** [cyaxaress/lms#2]
@cyaxaress 
سلام
بنده طبق آموزش پیش رفتم منتها این پیغام too many requests نشون داده میشه و نمیتونم ثبت نام کاربر جدید رو انجام بدم.
این مشکل مربوط به جلسه ی ۵۱ هست .
کد صفحه ی 
modules/cyaxaress/Dashboard/Routes/dashboard_routes 
رو به این صورت نوشتم
`<?php

Route::group([
    'namespace'=>'cyaxaress\Dashboard\Http\Controllers',
    'middleware'=>['web','auth','verified']
],function ($router){
    Route::get('/home','DashboardController@home')->name('home');

});`
HomeController رو هم کاملا درست نوشتم

`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth' , 'verified']);
    }

    public function index()
    {
        return view('home');
    }
}
`

**Comment by cyaxaress** [comment]
سلام مشکل شما در route هاتون بود
طوری که هر دو روت مربوط به نمایش فرم و پروسه عملیات وریفای رو به یه متد ارسال کرده بودید
`    Route::post('/email/verify','Auth\VerificationController@verify')->name('verification.verify');
    Route::get('/email/verify','Auth\VerificationController@verify')->name('verification.notice');`

که باید به این شکل اصلاج شود
`    Route::post('/email/verify','Auth\VerificationController@verify')->name('verification.verify');
    Route::get('/email/verify','Auth\VerificationController@show')->name('verification.notice');`
