### ISSUE TITLE
مشکل ارسال پیام به تلگرام

### ISSUE THREAD

**Issue by miladev-ent** [cyaxaress/lms#20]
سلام خسته نباشید 
زمانی که منو کامنت رو ذخیره میکنم و میخواد به تلگرام پیام بده این ارور رو میده
The communication with Telegram failed. `GuzzleHttp\Exception\ConnectException: cURL error 28: Failed to connect to api.telegram.org port 443: Timed out

**Comment by Omid-Zahed** [comment]
این به خاطر این هستش احتمالا از ip ایران درخواست میفرستید و ایران سرور تلگرام فیلتر کرده
یا اگر از پروکسی استفاده می کنید پروکسی به مشکل خورده
