### ISSUE TITLE
migrate 

### ISSUE THREAD

**Issue by abolfazlnorzad** [cyaxaress/lms#3]
Hi, when I use the php artisan migrate:fresh , I get the following error ( Your Code :  Episode 89)

` SQLSTATE[HY000]: General error: 1005 Can't create table `laravel`.`courses` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `courses` add constraint `courses_banner_id_foreign` foreign key (`banner_id`) references `media` (`id`) on delete SET NULL)

  at C:\Users\Ab01fa31\Downloads\Compressed\lms-e89\lms-e89\vendor\laravel\framework\src\Illuminate\Database\Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

  1   C:\Users\Ab01fa31\Downloads\Compressed\lms-e89\lms-e89\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:129
      Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `laravel`.`courses` (errno: 150 "Foreign key constraint is incorrectly formed")")

  2   C:\Users\Ab01fa31\Downloads\Compressed\lms-e89\lms-e89\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:127
      PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `laravel`.`courses` (errno: 150 "Foreign key constraint is incorrectly formed")`

**Comment by cyaxaress** [comment]
to solve this error just rename 
`modules/Cyaxaress/Media/Database/Migrations/2020_07_30_113119_create_media_table.php`
to
`modules/Cyaxaress/Media/Database/Migrations/2020_06_30_113119_create_media_table.php`

**Comment by abolfazlnorzad** [comment]
Thanks, but what is the cause of this error? This error is repeated in e108, but for "users" and "media" tables, how do i fix this?

`
  SQLSTATE[HY000]: General error: 1005 Can't create table `laravel`.`users` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `users` add constraint `users_image_id_foreign` foreign key (`image_id`) references `media` (`id`) on delete SET NULL)

  at C:\Users\Ab01fa31\Downloads\Compressed\lms-master\lms-master\vendor\laravel\framework\src\Illuminate\Database\Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

  1   C:\Users\Ab01fa31\Downloads\Compressed\lms-master\lms-master\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:131
      Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `laravel`.`users` (errno: 150 "Foreign key constraint is incorrectly formed")")

  2   C:\Users\Ab01fa31\Downloads\Compressed\lms-master\lms-master\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:129
      PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `laravel`.`users` (errno: 150 "Foreign key constraint is incorrectly formed")")
`

**Comment by cyaxaress** [comment]
Laravel performs migrations in order of name and gives an error because the media table was created after the course table. This problem was solved by changing the name of Migration.

**Comment by MH-Zarkhani** [comment]
for run migration in first time you can comment relation 

`$table->foreign('image_id')->references('id')->on('media')->onDelete('SET NULL');`

 in migration file and run migrate again

all migration run order creation date and users table always is oldest migration in laravel 

I think it's better that separate relation in new migration
like  :

`create_users_table`
`create_users_relations`

with this solution if create new module that have relation with another modules 
we can change just relation migration date to sort with correct date   
and prevent this error in future @cyaxaress
