### ISSUE TITLE
تست نویسی 

### ISSUE THREAD

**Issue by IBMBAROOEI** [cyaxaress/lms#34]
میخاستم بدونم که ایا نیاز هست که برا ی هر ماژول یک فایل کامپوزر بسازیم و هر ماژول کامپوزر خودش رو داشته باشه  و سوال بعدی چرا از Mockin استفاده نشده چون  الان من برای api قسمت جنریت کردن توکن رو داخل یک تابع دیگه نوشتم و الان میخام تستش رو بنویسم  میخام بدونم ازروش moking استفاده کنم

**Comment by cyaxaress** [comment]
الزامی به اینکار نیست. ولی اگر میخواید میتونید اینکارو بکنید. باعث میشه هر ماژول دپندسی هاش هم کار خودش باشه. 
من خودم ترجیح نمیدم حداقل الان اینکارو بکنم. 
برای ماک کردن بله باید ای پی آی هایی که به بیرون میزنید رو ماک بکنید تا واقعا اون درخواست رو نره و انحام نده.
