### ISSUE TITLE
مشکل در ادیت کردن  جلسه

### ISSUE THREAD

**Issue by mehrdad7027R** [cyaxaress/lms#5]
سلام من وقتی روی بخش ادیت کلیک میکنم   
url  درسته اما 404 میده
`    $router->get('courses/{course}/lessons/{lesson}/edit' , 'LessonController@edit')->name('lessons.edit');
`

http://localhost:8000/courses/2/lessons/1/edit

**Comment by cyaxaress** [comment]
سلام عزیز. له جلسات بعدتر برید اگر مشکلی بوده باشه برطرف کردیم
