### ISSUE TITLE
ارور Target class [view.engine.resolver] does not exist.

### ISSUE THREAD

**Issue by saeid13623** [cyaxaress/lms#6]
سلام جناب مهندس . من به ارور زیر برخور کردم
Target class [view.engine.resolver] does not exist.
 C:\Users\saeid\Desktop\website\vendor\laravel\framework\src\Illuminate\Container\Container.php:809
      ReflectionException::("Class view.engine.resolver does not exist")

composer dumpautoloadوقتی مینویسم
این ارور میده

permissionبع از نصب پکیج
این مشکل پیش آمد .

ممنون میشم راهنماییم کنید

**Comment by cyaxaress** [comment]
سلام 
این دستور رو توی رووت پروژه بزنید 
`composer dump-autoload -o`
