### ISSUE TITLE
error when send email for password recovery

### ISSUE THREAD

**Issue by faridepc78** [cyaxaress/lms#8]
سلام یه مشکلی هست اونم اینه که هنگام بازیابی رمز عبور 
یه گزنیه داریم به نام ارسال  مجدد کد فعال سازی که روش کلیک میشه میفرسته به صفحه لاگین کاربر رو و ایمیل هم ارسال نمیشه
احتمالا مشکل از روت ها باید باشه
و مشکل دیگه اینه که الان با هر با رفرش صفحه که کد منقضی شده باشه ایمیل ارسال میشه در صورتی که فقط با گزنیه ارسال مجدد باید کد ارسال بشه و این زیاد جالب و منظقی یست
متشکرم لطفا تست و فیکس کنید

**Comment by cyaxaress** [comment]
سلام عزیز وقت بخیر.  بررسی شد و در ارسال ایمیل مشکلی نیست و ارسال میشه. برای جلوگیری از ارسال مجدد با هر ریفرش میشه محدودیت زمانی گذاشت که هر 2 دقیقه یک بار کاربر بتونه درخواست تعییر رمز عبور بده. که این امر باست کردن یه middleware به اسم throttle امکان پدیره به راحتی
